### ISSUE TITLE
Issue on VAD Initialization

### ISSUE THREAD

**Issue by jhoelzl** [mwv/vad#2]
Hello,

i have installed the module and want to run this code:

```

#!/usr/bin/python
# -*- coding: utf-8 -*-

from vad import VAD
detector = VAD()
```

However, i get this error:

>   detector = VAD()
> TypeError: **init**() takes at least 2 arguments (1 given)

Any suggestions? Thanks!

**Comment by mwv** [comment]
The VAD needs the sampling rate as the first parameter.

fs = 16000
detector = VAD(fs)

**Comment by jhoelzl** [comment]
Thanks, works!
