### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by onsunsl** [mwv/vad#9]
File "C:\Anaconda3\lib\site-packages\vad-0.1.0-py3.5.egg\vad\_vad.py", line 114, in stft
    cols = int(np.ceil((s.shape[0] - self.wlen) / self.fshift + 1))
IndexError: tuple index out of range

**Comment by mwv** [comment]
Can you provide code to reproduce this error?

**Comment by waithope** [comment]
same error.
```
from _vad import VAD
detector = VAD(fs=16000)
speech = detector.detect_speech('sample_audio.wav')
```
## error occured
cols = int(np.ceil((s.shape[0] - self.wlen) / self.fshift + 1))
IndexError: tuple index out of range
